services:
  web:
    build: ./web
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - app-net

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db
    networks:
      - app-net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-net

  scheduler:
    build: ./scheduler
    env_file:
      - .env
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - app-net

  worker:
    build: ./worker
    env_file:
      - .env
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - app-net

networks:
  app-net:

volumes:
  mongo-data:
